version: '3'

services:
  spring-boot-aws-terraform:
    container_name: spring-boot-aws-terraform
    image: spring-boot-aws-terraform:latest
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: qa
      TZ: "America/Sao_Paulo"
    ports:
      - "80:8080"
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge